### ISSUE TITLE
Analytics Beta (v.4): 422 Unprocessable Entity error for custom string Eneity ID

### ISSUE THREAD

**Issue by Zenulous** [yext/analytics#136]
Hi there,

We attempted to migrate to the Beta library and encounter 422 errors when sending events. This is the case if our event contains a reference to an entity. It seems that when we use custom entities where the ID is a custom string that the analytics API continuously throws a 422 error.

![Image](https://github.com/yext/analytics/assets/45333650/17091be0-e303-4bef-8269-d820168d9858)

**Comment by AjayBenno** [comment]
Hi there,

Thank you for reporting the issue. Investigating the downstream error in the response we sent it seems that the length of the entity_id sent in seems to be exceeding the limits we set internally. We're investigating if those are set correctly and can come back to you.

In the meantime, do you mind confirming what you are migrating to using the new beta library for? I saw some information about search utilized in the request logs but unfortunately, that work to implement search in the new provider was done pre-maturely on our end(as in the downstream system's were not connected).

As of now, the only product we [support](https://hitchhikers.yext.com/docs/eventsapis/introduction/overview-policies-and-conventions/?target=hh-docs-eventsapis-introduction-overview-policies-and-conventions) on the new API is **Chat**.

Apologies for that. We're going to update the SDK to more clearly indicate that search features are not available for use yet. 

~Ajay

**Comment by AjayBenno** [comment]
Ah ok i think i understand the issue. We can go ahead and fix up reporting on firefox so that it falls back to beacon on the latest stable version so that you guys can have this behavior fixed.

The beta version does fix this but as i mentioned before the way it reports doesn't surface the data for in-platform analytics yet so i wouldn't recommend it.

I'll keep this thread updated as we implement the beacon support for the latest stable version.

**Comment by jennysharps** [comment]
Sounds good, thanks @AjayBenno!

**Comment by AjayBenno** [comment]
Hi all, https://github.com/yext/analytics/releases/tag/v0.6.6 has been released and this should allow for a beacon fallback when the browser does not support it. I'd recommend upgrading to v0.6.6!


The entity issue has also been fixed downstream so the entity id that you guys previously passed in should work as expect in the beta library as well. I'll be closing this issue as the reported bugs have been fixed, thank you for reporting everything!
